#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/2.5.0/
#+TITLE: Python Strings
#+AUTHOR: Jason Furtney
#+EMAIL: @jkfurtney
#+OPTIONS: toc:nil num:nil
* Strings

#+BEGIN_SRC python :session :exports both
string_1 = "My first string"
string_2 = 'Another string'

def my_function(input_string):
   """
   This is a multi-line docstring which describes what this functions does.
   Return an upper case copy of the input string.
   """
   return input_string.upper()

my_function(string_1)
#+END_SRC

* Basic string operations

#+BEGIN_SRC python :session :exports both
"Spam " + "eggs"
#+END_SRC

#+REVEAL: split

#+BEGIN_SRC python :session :exports both
"Spam "*10
#+END_SRC

#+REVEAL: split

#+BEGIN_SRC python :session :exports both
", ".join(["one", "two", "three"])
#+END_SRC

#+REVEAL: split

#+BEGIN_SRC python :session :exports both
str(42) == int("42")
#+END_SRC

#+REVEAL: split
** searching strings
#+BEGIN_SRC python :session :exports both
great_gatsby =  "A cautionary tale of the decadent downside of the American dream."
print "of" in great_gatsby
print great_gatsby.find("tale")
print great_gatsby.find("Python")
#+END_SRC

#+BEGIN_SRC python :session :exports both
book_text = """
In my younger and more vulnerable years my father gave me some advice
that I've been turning over in my mind ever since. "Whenever you feel
like criticizing any one", he told me, "just remember that all the
people in this world haven't had the advantages that you've had."
"""


#+END_SRC

* In the old days
   :PROPERTIES:
   :reveal_background: ./dumb_terminal.gif
   :reveal_background_trans: slide
   :END:

** .
   :PROPERTIES:
   :reveal_background: ./paper_tape_reader.gif
   :END:

** Structured Output

String interpolation with %
#+BEGIN_SRC python :session :exports both
"%s and %s" % ("Spam", "eggs")
#+END_SRC

The string .format() method
#+BEGIN_SRC python :session :exports both
"{} and {}".format("Spam", "eggs")
#+END_SRC

The .format() method is new (Python 2.6+) and is generally better. It
is extensible.

#+REVEAL: split

* Creating strings

Creating strings:
literal syntax
+, *, join,

beginswith()
endswith()

Structured output:
%, the interpolation operator
format
templates

json
xml

Breaking string apart:

indexing and slicing.
the split method.
partition

More advanced topics:

- raw strings
- unicode, Python 2 vs Python 3

clformat

string object methods, string module

Python strings are immutable, like tuples:

- Performance, objects can be reused
- Use as dictonary keys
- Safety, easier multi-treading
